### ISSUE TITLE
Plugin stopped working with update to Hogfather

### ISSUE THREAD

**Issue by brozkeff** [stonier/dokuwiki_plugins#5]
Before update to Dokuwiki "Hogfather" the plugin worked without error (Greebo).

Updating to Hogfather leads to 

Fatal error: Declaration of action_plugin_multilingual::register(&$controller) must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in /data/www/21580/(DOMAIN)/wiki/lib/plugins/multilingual/action.php on line 39

**Comment by stonier** [comment]
Resolved in #6 and #7. Released in 1.0.2 (also updated [instructions](https://www.dokuwiki.org/plugin:multilingual))
